USE MALM;

CREATE TABLE HUMAN (
	HUMAN_ID INT IDENTITY PRIMARY KEY,
	FIRSTNAME VARCHAR(20) NOT NULL,
	LASTNAME VARCHAR(40) NOT NULL,
	BIRTHDAY DATE
	);

CREATE TABLE PRESENCE (
	ID_HUMAN INT NOT NULL,
	DIA DATE NOT NULL,
	CONSTRAINT PK_Presence PRIMARY KEY CLUSTERED (ID_HUMAN, DIA),
	CONSTRAINT FK_HumanPresence FOREIGN KEY (ID_HUMAN) REFERENCES HUMAN(HUMAN_ID)
	);

INSERT INTO HUMAN (FIRSTNAME, LASTNAME) VALUES ('Jimmy', 'Feliber');

INSERT INTO PRESENCE (DIA, ID_HUMAN) VALUES ('2015-12-17', 1);

SELECT * FROM PRESENCE WHERE DIA = convert(varchar(30), cast('09/23/2019' as datetime), 102) AND ID_HUMAN = 6
IF @@ROWCOUNT = 0
    INSERT INTO PRESENCE(DIA, ID_HUMAN) VALUES(convert(varchar(30), cast('09/23/2019' as datetime), 102), 6)

SELECT DIA, DATEDIFF(DAY, '09/23/2019', DIA)+1 AS WEEKDAY FROM (
SELECT DIA
FROM PRESENCE WHERE ID_HUMAN = 1 AND DIA BETWEEN CONVERT(VARCHAR(30), CAST('09/23/2019' AS DATETIME), 102)
AND CONVERT(VARCHAR(30), CAST('09/29/2019' AS DATETIME), 102)) AS SUB_QUERY

DELETE FROM PRESENCE WHERE DIA = CONVERT(VARCHAR(30), CAST('09/26/2019' AS DATETIME), 102) AND ID_HUMAN = 1;

SELECT * FROM Human;

SELECT * FROM Presence;

DELETE FROM Human WHERE FIRSTNAME = 'JULIE'

DROP TABLE HUMAN;

DROP TABLE Presence;

SELECT HUMAN_ID, (1-HUMAN_ID) FROM HUMAN;