USE MALM;

CREATE TABLE PERSON (
	PERSON_ID INT IDENTITY PRIMARY KEY,
	FIRSTNAME VARCHAR(40) NOT NULL,
	LASTNAME VARCHAR(100) NOT NULL,
	BIRTHDAY DATE,
	WORKER BIT DEFAULT 0 NOT NULL
	);

CREATE TABLE PROGRAM (
	PROGRAM_ID INT IDENTITY PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL--,
	--ID_EDUCATOR INT NOT NULL,
	--CONSTRAINT FK_ProgramEducator FOREIGN KEY (ID_EDUCATOR) REFERENCES PERSON(PERSON_ID)
	);

CREATE TABLE PERSON_PROGRAM ( -- not useful anymore since we assign person's to groups now (PERSON_GROUP)
	ID_PERSON INT NOT NULL,
	ID_PROGRAM INT NOT NULL,
	CONSTRAINT FK_PersonID FOREIGN KEY (ID_PERSON) REFERENCES PERSON(PERSON_ID),
	CONSTRAINT FK_ProgramID FOREIGN KEY (ID_PROGRAM) REFERENCES PROGRAM(PROGRAM_ID)
	);

CREATE TABLE PRESENCE (
	ID_PERSON INT NOT NULL,
	DIA DATE NOT NULL,
	CONSTRAINT PK_Presence PRIMARY KEY CLUSTERED (ID_PERSON, DIA),
	CONSTRAINT FK_PersonPresence FOREIGN KEY (ID_PERSON) REFERENCES PERSON(PERSON_ID)
	);

CREATE TABLE WEEKLY_PRESENCE (
	ID_PERSON INT NOT NULL,
	WEEK_DAY INT NOT NULL,
	CONSTRAINT PK_WeeklyPresence PRIMARY KEY CLUSTERED (ID_PERSON, WEEK_DAY),
	CONSTRAINT FK_PersonWeeklyPresence FOREIGN KEY (ID_PERSON) REFERENCES PERSON(PERSON_ID)
	);

CREATE TABLE SERVICIO (
	SERVICIO_ID INT IDENTITY PRIMARY KEY,
	ID_PROGRAM INT NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	CONSTRAINT FK_ProgramServicio FOREIGN KEY (ID_PROGRAM) REFERENCES PROGRAM(PROGRAM_ID)
	);

CREATE TABLE GRUPO (
	GRUPO_ID INT PRIMARY KEY,
	ID_SERVICIO INT NOT NULL,
	ID_PERSON INT NOT NULL,
	NAME VARCHAR(30) NOT NULL, -- does the group have a name?
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL,
	CONSTRAINT FK_ServicioGrupo FOREIGN KEY (ID_SERVICIO) REFERENCES SERVICIO(SERVICIO_ID),
	CONSTRAINT FK_PersonGrupo FOREIGN KEY (ID_PERSON) REFERENCES PERSON(PERSON_ID)
	);

CREATE TABLE PERSON_GRUPO (
	ID_PERSON INT NOT NULL,
	ID_GRUPO INT NOT NULL,
	CONSTRAINT PK_PersonGrupo PRIMARY KEY CLUSTERED (ID_PERSON, ID_GRUPO),
	CONSTRAINT FK_PersonGrupo_PersonID FOREIGN KEY (ID_PERSON) REFERENCES PERSON(PERSON_ID),
	CONSTRAINT FK_PersonGrupo_GrupoID FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO(GRUPO_ID)
	);

INSERT INTO PERSON (FIRSTNAME, LASTNAME) VALUES ('Jimmy', 'Feliber');

INSERT INTO PRESENCE (DIA, ID_PERSON) VALUES ('2015-12-17', 1);

SELECT * FROM PRESENCE WHERE DIA = convert(varchar(30), cast('09/23/2019' as datetime), 102) AND ID_PERSON = 6
IF @@ROWCOUNT = 0
    INSERT INTO PRESENCE(DIA, ID_PERSON) VALUES(convert(varchar(30), cast('09/23/2019' as datetime), 102), 6)

SELECT DIA, DATEDIFF(DAY, '09/23/2019', DIA)+1 AS WEEKDAY FROM (
SELECT DIA
FROM PRESENCE WHERE ID_PERSON = 1 AND DIA BETWEEN CONVERT(VARCHAR(30), CAST('09/23/2019' AS DATETIME), 102)
AND CONVERT(VARCHAR(30), CAST('09/29/2019' AS DATETIME), 102)) AS SUB_QUERY

DELETE FROM PRESENCE WHERE DIA = CONVERT(VARCHAR(30), CAST('09/26/2019' AS DATETIME), 102) AND ID_PERSON = 1;

SELECT * FROM PERSON;

SELECT * FROM Presence;

SELECT * FROM PERSON_PROGRAM;

SELECT * FROM WEEKLY_PRESENCE;

SELECT * FROM PROGRAM;

SELECT * FROM SERVICIO;

SELECT * FROM GRUPO;

SELECT * FROM PERSON_GRUPO;

DELETE FROM PERSON WHERE FIRSTNAME = 'JULIE'

DROP TABLE PERSON;

DROP TABLE PRESENCE;

DROP TABLE WEEKLY_PRESENCE;

DROP TABLE PROGRAM;

DROP TABLE PERSON_PROGRAM;

DROP TABLE SERVICIO;

DROP TABLE GRUPO;

SELECT PERSON_ID AS ID, (FIRSTNAME + ' ' + LASTNAME) AS NAME FROM PERSON WHERE PERSON_ID IN (SELECT ID_PERSON FROM PERSON_PROGRAM WHERE ID_PROGRAM = 4);

SELECT * FROM PERSON_PROGRAM WHERE ID_PERSON = 24;

DELETE FROM PERSON;

DELETE FROM PERSON_PROGRAM;

DELETE FROM PROGRAM;

SELECT GRUPO_ID AS ID, GRUPO.NAME+' ('+CONVERT(NVARCHAR,GRUPO_ID)+')' AS NAME, START_DATE, END_DATE FROM GRUPO WHERE ID_SERVICIO IN (SELECT SERVICIO_ID FROM SERVICIO WHERE ID_PROGRAM = 1);

SELECT GRUPO_ID, NAME, CONVERT(VARCHAR, START_DATE, 103) AS START_DATE, CONVERT(VARCHAR, END_DATE, 103) AS END_DATE FROM GRUPO WHERE GRUPO_ID = 150001;