CREATE TABLE HUMAN (
	ID INT IDENTITY,
	FIRSTNAME VARCHAR(20) NOT NULL,
	LASTNAME VARCHAR(40) NOT NULL,
	BIRTHDAY DATE
	);

INSERT INTO HUMAN (FIRSTNAME, LASTNAME) VALUES ('Jimmy', 'Feliber');

SELECT * FROM Human;

DELETE FROM Human WHERE FIRSTNAME = 'JULIE';